---
- name: create leaf
  hosts: apic
  connection: local
  gather_facts: false

  tasks:

  - name: Add Leaf to APIC
    cisco.aci.aci_rest:
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    method: post
    path: /api/node/mo/uni/controller/nodeidentpol/nodep-aa.json
    content: {
  "fabricNodeIdentP": {
    "attributes": {
      "dn": "uni/controller/nodeidentpol/nodep-aa",
      "serial": "aa",
      "nodeId": "501",
      "name": "A-L501",
      "role": "leaf",
      "rn": "nodep-aa",
      "status": "created"
    },
    "children": []
  }
}
