---
- name: include creds
  hosts: aci
  connection: local
  gather_facts: false
  vars_files:
    - creds.yml
    - vars.yml

  tasks:

    - name: Add Bridge Domain
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ tenant }}"
        bd: "{{ bd-1 }}"
        mac_address: 00:22:BD:F8:19:FE
        vrf: "{{ vrf }}"
        state: present