---
- name: include creds
  hosts: aci
  connection: local
  gather_facts: false
  vars_files:
    creds.yml

  tasks:
  
  - name: add phys domain
    aci_domain:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      domain: dc2_phys_domain
      domain_type: phys
      state: present
      validate_certs: no
  - name: Bind a physical domain to VLAN pool
    aci_domain_to_vlan_pool:
      domain: dc2_phys_domain
      domain_type: phys
      pool: dc2-vlans
      pool_allocation_mode: static
      state: present
      validate_certs: no 