---
- name: include creds
  hosts: aci
  connection: local
  gather_facts: false
  vars_files:
    creds.yml

  tasks:
  
  - name: Create leaf profile
    aci_interface_policy_leaf_profile:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_interface_profile: dc2-ints
      state: present
      validate_certs: no
  - name: Associate an Interface Access Port Selector to an Interface Policy Leaf Profile with a Policy Group
    aci_access_port_to_interface_policy_leaf_profile:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_interface_profile: dc2-ints
      access_port_selector: dc2-ints
      leaf_port_blk: port-4
      from_port: 4
      to_port: 4
      policy_group: dc2-polgro
      state: present
      validate_certs: no
  - name: Associate an access port block (single port) to an interface selector
    aci_access_port_block_to_access_port:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_interface_profile: dc2-ints
      access_port_selector: dc2-ports
      leaf_port_blk: port-4
      from_port: 4
      to_port: 4
      state: present
      validate_certs: no