---
- name: include creds
  hosts: aci
  connection: local
  gather_facts: false
  vars_files:
    creds.yml

  tasks:
  
  - name: Create leaf profile
    aci_switch_policy_leaf_profile:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_profile: dc2-leaves
      state: present
      validate_certs: no