---
- name: MSO Config
  hosts: mso
  gather_facts: no
  vars:
  creds: &login
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    state: present

  tasks:
    
    - name: Add a new static port to a site EPG
      cisco.mso.mso_schema_site_anp_epg_staticport:
        schema: DevNet
        site: Devnet_APIC
        template: Site-1
        anp: Chaos
        epg: Database
        type: port
        pod: pod-1
        leaf: 101
        path: eth1/1
        vlan: 126
        deployment_immediacy: immediate