---
- name: Create VLAN Pools
  hosts: apic
  connection: local
  gather_facts: no

  tasks:


  - name: Add a new VLAN pool
    cisco.aci.aci_vlan_pool:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      pool: Jacob_VLANs
      pool_allocation_mode: static
      description: Production VLANs
      state: present
    delegate_to: localhost
  
  - name: Add a new VLAN encap block
    cisco.aci.aci_vlan_pool_encap_block:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      pool: Jacob_VLANs
      block_name: "Jacob_VLANs_Block"
      block_start: 10
      block_end: 20
      pool_allocation_mode: static
      state: present
    delegate_to: localhost