
---
- name: Query EPGs in given tenant
  hosts: aci
  connection: local
  gather_facts: false
  vars_files:
    creds.yml

  tasks:
  - name: Query all EPGs
    aci_epg:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: query
    delegate_to: localhost
    register: query_result