---
- name: include creds
  hosts: apic
  connection: local
  gather_facts: false
  vars_files:
    - creds.yml
    - vars.yml

  tasks:
  
  - name: Add a new tenant
    cisco.aci.aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "cisco"
      state: present
      validate_certs: no
