---
- name: include creds
  hosts: aci
  connection: local
  gather_facts: false
  vars_files:
    creds.yml,
    vars.yml

  tasks:
  
  - name: Add a new tenant
    aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{ tenant }}"
      state: present
      validate_certs: no