---
- name: include creds
  hosts: aci
  connection: local
  gather_facts: false

  tasks:
  
  - name: create vlan pool
    cisco.aci.aci_vlan_pool:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      pool: dc2-vlans
      pool_allocation_mode: static
      state: present
      validate_certs: no

  - name: add vlan block
    cisco.aci.aci_vlan_pool_encap_block:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      pool: dc2-vlans
      block_name: vlans
      block_start: 10
      block_end: 100
      pool_allocation_mode: static
      state: present
      validate_certs: no