---
- name: Configure ACI Tenant Policies
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    creds: &login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no


  tasks:
- name: Add a new tenant
  cisco.aci.aci_tenant:
    host: apic
    username: admin
    password: SomeSecretPassword
    tenant: production
    description: Production tenant
    state: present
  delegate_to: localhost

  - name: Create Tenants
    cisco.aci.aci_tenant:
      <<: *login
      tenant: "{{ tenant }}"
