---
- name: Configure ACI Tenant Policies
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    creds: &login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no


  tasks:

  - name: Create Tenants
    cisco.aci.aci_tenant:
      <<: *login
      tenant: "{{ tenant }}"

  - name: Create VRF
    cisco.aci.aci_vrf:
     <<: *login
     vrf: "{{ vrf }}"
     tenant: "{{ tenant }}"

  - name: Create BDs
    cisco.aci.aci_bd:
      <<: *login
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      bd: "{{ item  }}"
    loop:
      "{{ bridge_domains }}"

  - name: Create subnets in BDs
    cisco.aci.aci_bd_subnet:
      <<: *login
      tenant: "{{ tenant }}"
      bd: "{{ item.bd }}"
      gateway: "{{ item.gw }}"
      mask: 24
    loop:
      "{{ bd_subnets }}"

  - name: Create Application Profile
    cisco.aci.aci_ap:
      <<: *login
      tenant: "{{ tenant }}"
      ap: "{{ app_profile }}"

  - name: Create EPGs
    cisco.aci.aci_epg:
      <<: *login
      tenant: "{{ tenant }}"
      ap: "{{ app_profile }}"
      epg: "{{ item.epg }}"
      bd: "{{ item.bd }}"
    loop:
      "{{ epgs }}"

  - name: Create Contract
    cisco.aci.aci_contract:
     <<: *login
     tenant: "{{ tenant }}"
     contract: "{{ contract }}"

- name: Add a new contract subject
  cisco.aci.aci_contract_subject:
    <<: *login
    tenant: "{{ tenant }}"
    contract: "{{ contract }}"
    subject: "{{ subject }}"

  - name: Create Filter
    cisco.aci.aci_filter:
      <<: *login
      tenant: "{{ tenant }}"
      filter: "{{ filter }}"

  - name: Create Filter Entry
    cisco.aci.aci_filter_entry:
      <<: *login
      tenant: "{{ tenant }}"
      entry: "{{ entry }}"
      ether_type: "{{ ether_type }}"
      ip_protocol: "{{ protocol }}"
      dst_port: "{{ port }}"
      filter: "{{ filter }}"
