---
- name: Configure ACI Tenant Policies
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    creds: &login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no


  tasks:

  - name: Create Tenants
    cisco.aci.aci_tenant:
      <<: *login
      tenant: "{{ tenant }}"

  - name: Create VRF
    cisco.aci.aci_vrf:
     <<: *login
     vrf: "{{ vrf }}"
     tenant: "{{ tenant }}"

  - name: Create BDs
    cisco.aci.aci_bd:
      <<: *login
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      bd: "{{ item  }}"
    loop:
      "{{ bridge_domains }}"

  - name: Query tenant status
    cisco.aci.aci_tenant:
      <<: *login
      tenant: "{{ tenant }}"
      state: query
    register: tenant_query

  - name: Create BDs
    cisco.aci.aci_bd:
      <<: *login
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      bd: "{{ item  }}"
    loop:
      "{{ bridge_domains }}"
    register: bd_query

  - name: Print debug
    debug: msg="{{ tenant_query }}"
