---
- name: Configure ACI Tenant Policies
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    creds: &login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no


  tasks:

  - name: Create Tenants
    cisco.aci.aci_tenant:
      <<: *login
      tenant: "{{ tenant }}"

  - name: Create VRF
    cisco.aci.aci_vrf:
     <<: *login
     vrf: "{{ vrf }}"
     tenant: "{{ tenant }}"
