tenant: Student_Tenant
vrf: production

bridge_domains:
- Web_BD
- App_BD
- DB_BD


bd_subnets:
  - { bd: "Web_BD", gw: "10.0.1.1" }
  - { bd: "App_BD", gw: "10.0.2.1" }
  - { bd: "DB_BD", gw: "10.0.3.1" }

app_profile: web_app
