tenant: Student_Tenant
vrf: production

bridge_domains:
- Web_BD
- App_BD
- DB_BD


bd_subnets:
  - { bd: "Web_BD", gw: "10.0.1.1" }
  - { bd: "App_BD", gw: "10.0.2.1" }
  - { bd: "DB_BD", gw: "10.0.3.1" }

app_profile: web_app

epgs:
  - { epg: "Web", bd: "Web_BD"}
  - { epg: "App", bd: "App_BD"}
  - { epg: "DB", bd: "DB_BD"}

contract: app_to_db



filter: SSH_filter

entry: SSH
ether_type: ip
protocol: tcp
port: "22"
