tenant: Student_Tenant

app_profile: db_app
vrf: production

epgs_bds:
- { tenant: "Learning_Tenant_1", bd: "Web_BD", epg: "Web" }
- { tenant: "Learning_Tenant_1", bd: "App_BD", epg: "App"}
- { tenant: "Learning_Tenant_1", bd: "DB_BD", epg: "DB" }
- { tenant: "Learning_Tenant_2", bd: "Web_BD", epg: "Web" }
- { tenant: "Learning_Tenant_2", bd: "App_BD", epg: "App" }
- { tenant: "Learning_Tenant_2", bd: "DB_BD", epg: "DB" }
