tenant: Student_Tenant
vrf: production
app_profile: web_app

bridge_domains:
- Web_BD
- App_DB
- DB_BD


bd_subnets:
  - { bd: "Web_BD", gw: "10.0.1.1" }
  - { bd: "App_BD", gw: "10.2.1.1"}
  - { bd: "DB_BD", gw: "10.0.3.1" }
